# Zsh plugins
[".config/zsh/plugins/zsh-completions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-completions"
refreshPeriod = "672h"

[".config/zsh/plugins/zsh-tab-title"]
type = "git-repo"
url = "https://github.com/trystan2k/zsh-tab-title"
refreshPeriod = "672h"

[".config/zsh/plugins/fast-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zdharma-continuum/fast-syntax-highlighting"
refreshPeriod = "672h"

[".config/zsh/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions"
refreshPeriod = "672h"

# Yazi plugins
[".config/yazi/plugins/exifaudio.yazi"]
type = "archive"
url = "https://github.com/Sonico98/exifaudio.yazi/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"

[".config/yazi/plugins/starship.yazi"]
type = "archive"
url = "https://github.com/Rolv-Apneseth/starship.yazi/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"

{{- if ne .chezmoi.os "linux" -}}
# Linux only external files
[".local/share/fonts/FiraCodeNerdFont"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.tar.xz"
refreshPeriod = "672h"
{{- end -}}
