[colors]
foreground = "#DCD7BA"
background = "#1F1F28"
cursor_bg = "#C8C093"
cursor_border = "#3760bf"
cursor_fg = "#3760bf"
selection_bg = "#2D4F67"
selection_fg = "#C8C093"

ansi = ["#16161D", "#C34043", "#76946A", "#C0A36E", "7E9CD8", "#957FB8", "#6A9589", "#C8C093"]
brights = ["#727169", "#E82424", "#98BB6C", "#E6C384", "#7FB4CA", "#938AA9", "#7AA89F", "#DCD7BA"]

[colors.tab_bar]
inactive_tab_edge = "#C8C093"
background = "#15161E"

[colors.tab_bar.active_tab]
fg_color = "#C8C093"
bg_color = "#1F1F28"

[colors.tab_bar.inactive_tab]
bg_color = "#1F1F28"
fg_color = "#727169"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#C8C093"
fg_color = "#1F1F28"

[colors.tab_bar.new_tab_hover]
bg_color = "#C8C093"
fg_color = "#1F1F28"

[colors.tab_bar.new_tab]
fg_color = "#C8C093"
bg_color = "#15161E"

[colors.indexed] # I cannot find how to use these
# color16 #FFA066
# color17 #FF5D62

[metadata]
aliases = ["kanagawa wave"]
author = "Tommaso Laurenzi"
name = "kanagawa"
