[colors]
ansi = [
    "#1c1e1b",
    "#e75a7c",
    "#8fb573",
    "#dbb671",
    "#57a5e5",
    "#aaaaff",
    "#70c2be",
    "#f1e9d2",
]
brights = [
    "#5b5e5a",
    "#ff227c",
    "#73b969",
    "#f2b163",
    "#0098ed",
    "#9999ff",
    "#00c9bf",
    "#fff8f0",
]
background = "#452f32"
cursor_bg = "#fff8f0"
cursor_border = "#fff8f0"
cursor_fg = "#0f0800"
foreground = "#f1e9d2"
scrollbar_thumb = "#1c1e1b"
selection_bg = "#5b5e5a"
selection_fg = "#f1e9d2"
split = "#838781"
compose_cursor = "#ff9966"
visual_bell = "#383b35"

[colors.indexed]

[colors.tab_bar]
background = "#322022"
inactive_tab_edge = "#463536"

[colors.tab_bar.active_tab]
bg_color = "#e75a7c"
fg_color = "#111210"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#574243"
fg_color = "#838781"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#4e3839"
fg_color = "#838781"
intensity = "Normal"
italic = true
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#725d60"
fg_color = "#f1e9d2"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#948080"
fg_color = "#f1e9d2"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
name = 'Bamboo V'
author = 'Riley Bruins'
origin_url = "https://github.com/ribru17/bamboo.nvim"
