[colors]
foreground = "#c5c9c5"
background = "#181616"
cursor_bg = "#C8C093"
cursor_border = "#3760bf"
cursor_fg = "#3760bf"
selection_bg = "#2D4F67"
selection_fg = "#C8C093"

ansi = ["#0d0c0c", "#c4746e", "#8a9a7b", "#c4b28a", "#8ba4b0", "#a292a3", "#8ea4a2", "#C8C093"]
brights = ["#a6a69c", "#E46876", "#87a987", "#E6C384", "#7FB4CA", "#938AA9", "#7AA89F", "#c5c9c5"]

[colors.tab_bar]
inactive_tab_edge = "#C8C093"
background = "#282727"

[colors.tab_bar.active_tab]
fg_color = "#C4C9C5"
bg_color = "#12120f"

[colors.tab_bar.inactive_tab]
bg_color = "#12120f"
fg_color = "#C4C9C5"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#393836"
fg_color = "#1F1F28"

[colors.tab_bar.new_tab_hover]
bg_color = "#393836"
fg_color = "#1F1F28"

[colors.tab_bar.new_tab]
fg_color = "#C4C9C5"
bg_color = "#282727"

[colors.indexed] # I cannot find how to use these
# color16 #b6927b
# color17 #b98d7b

[metadata]
aliases = ["kanagawa dragon"]
author = "Tommaso Laurenzi"
name = "kanagawa dark"
