gui:
  nerdFontsVersion: "3"
  authorColors:
    'Eve Jensen': '#6d3dde'
os:
  editPreset: "nvim-remote"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
notARepository: 'skip'
