gui:
  nerdFontsVersion: "3"
os:
  edit: 'lvim -- {{filename}}'
  editAtLine: 'lvim +{{line}} -- {{filename}}'
  editAtLineAndWait: 'lvim +{{line}} -- {{filename}}'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
notARepository: 'skip'
