# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 2, 3]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true

[opener]
open = [
  { run = 'xdg-open "$@"', orphan = true, desc = "Open", for = "linux" },
  { run = 'open "$@"', desc = "Open", for = "macos" },
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
  { run = 'open -a "Hex Fiend" -- "$@"', orphan = true, desc = "Hex Fiend", for = "macos" },
  { run = '''hexyl "$1"; echo "Press enter to exit"; read''', block = true, desc = "Hexyl", for = "unix" },
]
play = [
  # For some god-forsaken reason I can't use the iina-cli, so I'll use "open" instead
  { run = 'open -a iina "$@"', orphan = true, for = "macos", desc = "IINA" },
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = 'mpv "%1"', orphan = true, for = "windows" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]

[plugin]
prepend_previewers = [
  { mime = "audio/midi", run = "hexfile" },
  { mime = "audio/*", run = "exifaudio" },  # exifaudio.yazi
]
append_previewers = [
  { name = "*", run = "hexfile" }, # Shows filetype and hexdump via hexyl
]
