-- Center cursor when scrolling
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<C-d>", "<C-d>zz")

-- Registers
vim.keymap.set("n", "<leader>d", "\"_d", { desc = "Delete without yank", })
vim.keymap.set("x", "<leader>d", "\"_d", { desc = "Delete without yank", })
vim.keymap.set("n", "<leader>y", "\"+y", { desc = "Yank into clipboard", })
vim.keymap.set("x", "<leader>y", "\"+y", { desc = "Yank into clipboard", })

-- Misc
local _e = "<CMD>lua MiniFiles.open(vim.api.nvim_buf_get_name(0))<CR>"
vim.keymap.set("n", "<leader>e", _e, { desc = "Open file explorer", })
vim.keymap.set("n", "<leader>E", "<CMD>lua MiniFiles.open()<CR>", { desc = "Open file explorer at CWD", })
vim.keymap.set("n", "<leader>h", "<CMD>nohlsearch<cr>", { desc = "Hide highlights", })
vim.keymap.set("n", "<leader>F", "<CMD>Format<cr>", { desc = "Format file", })
vim.keymap.set("n", "<leader>z", "<CMD>lua MiniMisc.zoom()<cr>", { desc = "Zoom", })

-- Find (using Snacks.picker)
vim.keymap.set("n", "<leader>f/", "<CMD>lua Snacks.picker.search_history()<CR>", { desc = "'/' history" })
vim.keymap.set("n", "<leader>f:", "<CMD>lua Snacks.picker.command_History<CR>", { desc = "':' history" })
vim.keymap.set("n", "<leader>f\"", "<CMD>lua Snacks.picker.registers()<CR>", { desc = "Registers" })
vim.keymap.set("n", "<leader>fb", "<CMD>lua Snacks.picker.buffers()<CR>", { desc = "Buffers" })
vim.keymap.set("n", "<leader>fc", "<CMD>lua Snacks.picker.qflist()<CR>", { desc = "Quickfix list" })
vim.keymap.set("n", "<leader>fd", "<CMD>lua Snacks.picker.diagnostics_buffer()<CR>", { desc = "Diagnostic buffer" })
vim.keymap.set("n", "<leader>fD", "<CMD>lua Snacks.picker.diagnostics()<CR>", { desc = "Diagnostic workspace" })
vim.keymap.set("n", "<leader>ff", "<CMD>lua Snacks.picker.files()<CR>", { desc = "Files" })
vim.keymap.set("n", "<leader>fF", "<CMD>lua Snacks.picker.files({hidden = true, ignored = true})<CR>",
  { desc = "All files" })
vim.keymap.set("n", "<leader>fg", "<CMD>lua Snacks.picker.grep()<CR>", { desc = "Grep" })
vim.keymap.set("n", "<leader>fGB", "<CMD>lua Snacks.picker.git_branches()<CR>", { desc = "Git branches (all)" })
vim.keymap.set("n", "<leader>fGH", "<CMD>lua Snacks.picker.git_diff()<CR>", { desc = "Modified hunks (all)" })
vim.keymap.set("n", "<leader>fh", "<CMD>lua Snacks.picker.help()<CR>", { desc = "Help" })
vim.keymap.set("n", "<leader>fH", "<CMD>lua Snacks.picker.highlights()<CR>", { desc = "Highlight groups" })
vim.keymap.set("n", "<leader>fk", "<CMD>lua Snacks.picker.keymaps()<CR>", { desc = "Keymaps" })
vim.keymap.set("n", "<leader>fl", "<CMD>lua Snacks.picker.lines()<CR>", { desc = "Lines (buf)" })
vim.keymap.set("n", "<leader>fm", "<CMD>lua Snacks.picker.marks()<CR>", { desc = "Marks" })
vim.keymap.set("n", "<leader>fM", "<CMD>lua Snacks.picker.man()<CR>", { desc = "Manpages" })
vim.keymap.set("n", "<leader>fp", "<CMD>lua Snacks.picker.pickers()<CR>", { desc = "Pickers" })
vim.keymap.set("n", "<leader>fr", "<CMD>lua Snacks.picker.lsp_references()<CR>", { desc = "References (LSP)" })
vim.keymap.set("n", "<leader>fR", "<CMD>lua Snacks.picker.resume()<CR>", { desc = "Resume" })
vim.keymap.set("n", "<leader>fs", "<CMD>lua Snacks.picker.lsp_symbols()<CR>", { desc = "Symbols document" })
vim.keymap.set("n", "<leader>fS", "<CMD>lua Snacks.picker.lsp_workspace_symbols()<CR>", { desc = "Symbols workspace" })
vim.keymap.set("n", "<leader>ft", "<CMD>lua Snacks.picker.treesitter()<CR>", { desc = "Treesitter" })
vim.keymap.set("n", "<leader>fT", "<CMD>lua Snacks.picker.tags()<CR>", { desc = "Tags" })
vim.keymap.set("n", "<leader>fz", "<CMD>lua Snacks.picker.spelling()<CR>", { desc = "Spelling suggestions" })

-- Pick (Using MiniPick)
vim.keymap.set("n", "<leader>p*", "<CMD>Pick grep pattern='<cword>'<CR>", { desc = "Grep current word" })
vim.keymap.set("n", "<leader>p/", "<CMD>Pick history scope='/'<CR>", { desc = "'/' history" })
vim.keymap.set("n", "<leader>p:", "<CMD>Pick history scope=':'<CR>", { desc = "':' history" })
vim.keymap.set("n", "<leader>pb", "<CMD>Pick buffers<CR>", { desc = "Buffers" })
vim.keymap.set("n", "<leader>pd", "<CMD>Pick diagnostic scope='current'<CR>", { desc = "Diagnostic buffer" })
vim.keymap.set("n", "<leader>pD", "<CMD>Pick diagnostic scope='all'<CR>", { desc = "Diagnostic workspace" })
vim.keymap.set("n", "<leader>pf", "<CMD>Pick files<CR>", { desc = "Files" })
local fF = "<CMD>lua MiniPick.builtin.cli({ command = { 'rg', '--files', '--color=never', '-uu', '-g=!.git/*' } })<CR>"
vim.keymap.set("n", "<leader>pF", fF, { desc = "All files" })
vim.keymap.set("n", "<leader>pg", "<CMD>Pick grep_live<CR>", { desc = "Grep" })
vim.keymap.set("n", "<leader>pGa", "<CMD>Pick git_hunks scope='staged' path='%'<CR>", { desc = "Added hunks (buf)" })
vim.keymap.set("n", "<leader>pGA", "<CMD>Pick git_hunks scope='staged'<CR>", { desc = "Added hunks (all)" })
vim.keymap.set("n", "<leader>pGb", "<CMD>Pick git_branches path='%'<CR>", { desc = "Git branches (buf)" })
vim.keymap.set("n", "<leader>pGB", "<CMD>Pick git_branches<CR>", { desc = "Git branches (all)" })
vim.keymap.set("n", "<leader>pGc", "<CMD>Pick git_commits path='%'<CR>", { desc = "Commits (buf)" })
vim.keymap.set("n", "<leader>pGC", "<CMD>Pick git_commits<CR>", { desc = "Commits (all)" })
vim.keymap.set("n", "<leader>pGh", "<CMD>Pick git_hunks path='%'<CR>", { desc = "Modified hunks (buf)" })
vim.keymap.set("n", "<leader>pGH", "<CMD>Pick git_hunks<CR>", { desc = "Modified hunks (all)" })
vim.keymap.set("n", "<leader>ph", "<CMD>Pick help<CR>", { desc = "Help" })
vim.keymap.set("n", "<leader>pH", "<CMD>Pick hl_groups<CR>", { desc = "Highlight groups" })
vim.keymap.set("n", "<leader>pl", "<CMD>Pick buf_lines scope='current'<CR>", { desc = "Lines (buf)" })
vim.keymap.set("n", "<leader>pL", "<CMD>Pick buf_lines scope='all'<CR>", { desc = "Lines (all)" })
vim.keymap.set("n", "<leader>pm", "<CMD>Pick marks<CR>", { desc = "Marks" })
vim.keymap.set("n", "<leader>pr", "<CMD>Pick lsp scope='references'<CR>", { desc = "References (LSP)" })
vim.keymap.set("n", "<leader>pR", "<CMD>Pick resume<CR>", { desc = "Resume" })
vim.keymap.set("n", "<leader>ps", "<CMD>Pick lsp scope='document_symbol'<CR>", { desc = "Symbols document" })
vim.keymap.set("n", "<leader>pS", "<CMD>Pick lsp scope='workspace_symbol_live'<CR>", { desc = "Symbols workspace" })
vim.keymap.set("n", "<leader>pz", "<CMD>Pick spellsuggest<CR>", { desc = "Spelling suggestions" })

-- Git
vim.keymap.set("n", "<leader>gb", "<CMD>Git blame -- %<CR>", { desc = "Git blame" })
vim.keymap.set("n", "<leader>gd", "<CMD>lua MiniDiff.toggle_overlay()<CR>", { desc = "Show/hide diff" })
vim.keymap.set("n", "<leader>gl", "<CMD>Git log --topo-order --follow -- %<CR>", { desc = "Git log for buffer" })
vim.keymap.set("n", "<leader>gL", "<CMD>Git log --topo-order<CR>", { desc = "Git log" })
vim.keymap.set("n", "<leader>gs", "<CMD>lua MiniGit.show_at_cursor()<CR>", { desc = "Show at cursor" })
