format = """$all$os$jobs$battery$time$status$sudo$container$shell$character"""
command_timeout = 1000

# Different prompt symbol
[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

# Battery
[[battery.display]]
threshold = 20 # default 10

# Command duration
[cmd_duration]
show_milliseconds = true

# Git
[git_metrics]
disabled = false

[os]
format = '[$symbol ]($style)'
disabled = true

# Status; essentially exit codes
[status]
format = '[$symbol$status]($style) '
disabled = false

[sudo]
format = '[$symbol]($style)'
symbol = '! '
disabled = true

[time]
disabled = true

# Symbols
[aws]
symbol = '󰸏 '

[azure]
symbol = '󰠅 '

[buf]
symbol = ' '

[c]
symbol = ' '

[cmake]
symbol = '󰔷 '

[conda]
symbol = '󱔎 '

[crystal]
symbol = ' '

[dart]
symbol = ' '

[directory]
read_only = ' 󰌾'

[docker_context]
symbol = ' '

[dotnet]
symbol = '󰪮 '

[elixir]
symbol = ' '

[elm]
symbol = ' '

[erlang]
symbol = ' '

[fossil_branch]
symbol = ' '

[git_branch]
symbol = ' '

[golang]
symbol = ' '

[guix_shell]
symbol = ' '

[gradle]
symbol = ' '

[haskell]
symbol = ' '

[haxe]
symbol = ' '

[hg_branch]
symbol = ' '

[hostname]
ssh_symbol = ' '

[java]
symbol = ' '

[julia]
symbol = ' '

[kotlin]
symbol = '󱈙 '

[kubernetes]
symbol = '󱃾 '

[lua]
symbol = ' '

[memory_usage]
symbol = '󰍛 '

[meson]
symbol = '󰔷 '

[nim]
symbol = ' '

[nix_shell]
symbol = ' '

[nodejs]
symbol = ' '

[os.symbols]
Alpaquita = ' '
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '󰛓 '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = ' '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = ' '
openSUSE = ' '
OracleLinux = '󰌷 '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
Redox = ' '
Solus = ' '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Windows = '󰨡 '

[package]
symbol = '󰏗 '

[perl]
symbol = ' '

[php]
symbol = ' '

[pijul_channel]
symbol = '󱗆 '

[purescript]
symbol = ' '

[python]
symbol = ' '

[rlang]
symbol = '󰟔 '

[raku]
symbol = ' '

[ruby]
symbol = ' '

[rust]
symbol = ' '

[scala]
symbol = ' '

[spack]
symbol = '🅢 '

[swift]
symbol = ' '

[terraform]
symbol = '󱁢 '

[vlang]
symbol = ' '

[zig]
symbol = ' '
